Fix Async Tree not keeping descendant nodes hidden
Lodin/react-vtree pull request #54
Opened 2021-03-02 18:33 UTC by HeavensRegent

Updated the createBasicRecord to also verify the parent isShown. Before it only checked to see if the parent was open.

2021-03-03 07:20 UTC, Lodin requested changes
Hi @HeavensRegent, thanks for contribution! Sorry for the late response, I'm kind of busy in the latest couple of months.

Could you also add tests for the change?

2021-03-03 18:47 UTC, HeavensRegent commented
I don't quite understand how to replicate the issue on the code side... more like I have no clue. I'm having a hard time making a test that fails on the current code and is being resolved on the proposed change.

The 2 main questions I have: I'm not sure how to trigger an async reload and I'm not sure how to access the property isShowing

2021-03-19 17:49 UTC, HeavensRegent commented
@Lodin Here is an attempt at updating the tests to verify the code I added. It doesn't work, but it's as far as I could get with my current understanding. https://github.com/HeavensRegent/react-vtree/tree/tests

2021-03-20 18:46 UTC, Lodin approved these changes
Sorry for the long response, that's really a busy time for me and I'm kinda outside of this project. I'm going to accept this PR without tests for now because the bug needs to be fixed. If you figure out the correct tests, feel free to open a new PR for that.

2021-03-20 18:47 UTC, merged

2021-03-20 19:15 UTC, Lodin commented
Published in `react-vtree@3.0.0-beta.1`. Note that now you need to use the `beta` tag to install the `3.0.0` version because I have released `3.0.0-beta.0` as `latest` by mistake.

Sorry again for the mess with the bugfix.